### ISSUE TITLE
&porn command is not working correctly

### ISSUE THREAD

**Issue by smpial** [whitetrashyt/r34discordbot#9] opened 2020-08-05 04:09 UTC
If I enter &porn or &porn OneTag, then everything works fine, and if I enter more than one tag or there is - in the tag, then embed is not sent, although the entered tags are written in the console. And if the tag contains _, then an error appears:

Ignoring exception in command porn:
Traceback (most recent call last):
  File "C:\Users\Спартак\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "main2.py", line 86, in porn
    answer = rdl(arg,1)
  File "main2.py", line 45, in rdl
    if 'webm' in wr.lstrip('.'):
AttributeError: 'NoneType' object has no attribute 'lstrip'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Спартак\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Спартак\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Спартак\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'lstrip'

What to do?

**Comment by whitetrashyt** [comment] 2020-08-05 17:04
Sorry for the late reply.

Does your bot properly post the image? If so, i know what is causing this issue, but it should be just a console stuffer

**Comment by whitetrashyt** [comment] 2020-08-05 17:56
Also, if your image is posting a webm and not a embed when you dont specify sound, that's an intentional thing. I'll look into the lstrip no attribute problem.

**Comment by whitetrashyt** [comment] 2020-08-05 17:57
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #9 (NoneType has no attribute lstrip)](https://trello.com/c/7sf6mrkQ/18-issue-9-nonetype-has-no-attribute-lstrip)

**Comment by whitetrashyt** [comment] 2020-08-05 18:02
What tags are you using that contain "-" that cause the error? my testing with Uzaki-chan_wa_asobitai and animated worked just fine.

**Comment by whitetrashyt** [comment] 2020-08-05 18:10
I believe this is caused by polling for a nonexistent tag, are you sure that you're polling for a very much real tag?

For ex:
&porn furry
That will return an image properly
&porn hello
That will return a nonetype because no tags of that type exist.

**Comment by whitetrashyt** [comment] 2020-08-05 18:21
this will also happen if you supply too many tags that rule34 cant find any, for example:

&porn uzaki-chan_wa_asobitai! sound rape

This returns no posts since theres no posts that have these exact tags

**Comment by smpial** [comment] 2020-08-06 06:20
I used real tags where they are - and the bot simply did not send messages, but the tag that I entered is written in the console. And when I try to enter several tags, the bot sends me an image only for the first tag

**Comment by whitetrashyt** [comment] 2020-08-06 06:52
I'll look into this ASAP. Are you using 2.0 or an earlier build?

**Comment by smpial** [comment] 2020-08-06 06:54
2.0

**Comment by whitetrashyt** [comment] 2020-08-06 06:55
Which tags did you use, so i can debug this with the same tags?

**Comment by whitetrashyt** [comment] 2020-08-06 07:05
I'm looking at the bot right now, it seems to be fine with dual tags (Animated + Sound returned a sound post, when it shouldn't unless it takes into account sound tag)

**Comment by whitetrashyt** [comment] 2020-08-06 07:08
Ah, no, i see it. Using animated, uzaki-chan_wa_asobitai, and big_boobs caused this same error. Seems like its breaking somehow.

I'll look into it

**Comment by whitetrashyt** [comment] 2020-08-06 07:11
Seems like an issue with rule34's api. I've verified that posts under these tags exist, however, the xml file returns empty.

**Comment by whitetrashyt** [comment] 2020-08-06 07:17
> 
> 
> Seems like an issue with rule34's api. I've verified that posts under these tags exist, however, the xml file returns empty.

Scratch that, its a relation to an earlier issue we faced regarding recursive functions sometimes exiting earlier than they're supposed to. I'll work on fixing this, but it may take a day or two.

**Comment by smpial** [comment] 2020-08-06 07:23
> Which tags did you use, so i can debug this with the same tags?

I have used many tags with - (for example: ugh-zan), and for two or more tags you can use any

> Scratch that, its a relation to an earlier issue we faced regarding recursive functions sometimes exiting earlier than they're supposed to. I'll work on fixing this, but it may take a day or two.

Okay, good luck!

**Comment by whitetrashyt** [comment] 2020-08-06 07:40
Right, the issues with - seemed to be an offset overflow (We're offsetting so much that if we choose the last one, it blanks) however, i have no clue if that's it. Should be fixed in 2.1 / commit 12c32be

as for double tag issue, i have no clue what's causing that. My debugging runs haven't been able to make that error appear for two tags, if you have any specific tags that cause that error it'd be of great help.

Source code should be up to date with commit 12c32be, i'll leave the issue open incase the commit doesn't fix the error.

**Comment by whitetrashyt** [comment] 2020-08-08 08:52
Since there's been no activity, i'll assume this has been fixed, leave a comment if it isn't and i'll reopen.

**Closed as completed** 2020-08-08 08:51 UTC
Labels: bug, Priority 1 issue
